# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Horizontal.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(678, 630)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("SMISlogo"))
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 546, 671, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.btnStop = QtGui.QPushButton(self.centralwidget)
        self.btnStop.setGeometry(QtCore.QRect(560, 320, 101, 101))
        self.btnStop.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Logo/129538-simple-red-square-icon-signs-z-roadsign20.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStop.setIcon(icon)
        self.btnStop.setIconSize(QtCore.QSize(130, 130))
        self.btnStop.setObjectName(_fromUtf8("btnStop"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-20, 40, 721, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(0, 420, 671, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.btnxh = QtGui.QPushButton(self.centralwidget)
        self.btnxh.setGeometry(QtCore.QRect(485, 271, 39, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btnxh.setFont(font)
        self.btnxh.setIconSize(QtCore.QSize(35, 35))
        self.btnxh.setObjectName(_fromUtf8("btnxh"))
        self.btnxb = QtGui.QPushButton(self.centralwidget)
        self.btnxb.setGeometry(QtCore.QRect(395, 270, 39, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btnxb.setFont(font)
        self.btnxb.setIconSize(QtCore.QSize(35, 35))
        self.btnxb.setObjectName(_fromUtf8("btnxb"))
        self.btnyb = QtGui.QPushButton(self.centralwidget)
        self.btnyb.setGeometry(QtCore.QRect(41, 391, 39, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btnyb.setFont(font)
        self.btnyb.setIconSize(QtCore.QSize(35, 35))
        self.btnyb.setObjectName(_fromUtf8("btnyb"))
        self.btnyh = QtGui.QPushButton(self.centralwidget)
        self.btnyh.setGeometry(QtCore.QRect(131, 391, 39, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btnyh.setFont(font)
        self.btnyh.setIconSize(QtCore.QSize(35, 35))
        self.btnyh.setObjectName(_fromUtf8("btnyh"))
        self.btnzb = QtGui.QPushButton(self.centralwidget)
        self.btnzb.setGeometry(QtCore.QRect(200, 117, 29, 39))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnzb.setFont(font)
        self.btnzb.setIconSize(QtCore.QSize(35, 35))
        self.btnzb.setObjectName(_fromUtf8("btnzb"))
        self.btnzh = QtGui.QPushButton(self.centralwidget)
        self.btnzh.setGeometry(QtCore.QRect(200, 50, 29, 39))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnzh.setFont(font)
        self.btnzh.setIconSize(QtCore.QSize(35, 35))
        self.btnzh.setObjectName(_fromUtf8("btnzh"))
        self.stepX = QtGui.QLineEdit(self.centralwidget)
        self.stepX.setGeometry(QtCore.QRect(440, 275, 39, 20))
        self.stepX.setCursorPosition(3)
        self.stepX.setAlignment(QtCore.Qt.AlignCenter)
        self.stepX.setReadOnly(False)
        self.stepX.setPlaceholderText(_fromUtf8(""))
        self.stepX.setObjectName(_fromUtf8("stepX"))
        self.stepY = QtGui.QLineEdit(self.centralwidget)
        self.stepY.setGeometry(QtCore.QRect(86, 395, 39, 20))
        self.stepY.setAlignment(QtCore.Qt.AlignCenter)
        self.stepY.setObjectName(_fromUtf8("stepY"))
        self.stepZ = QtGui.QLineEdit(self.centralwidget)
        self.stepZ.setGeometry(QtCore.QRect(196, 93, 39, 20))
        self.stepZ.setAlignment(QtCore.Qt.AlignCenter)
        self.stepZ.setObjectName(_fromUtf8("stepZ"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 431, 351, 121))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setSpacing(14)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.btnSaveP1 = QtGui.QPushButton(self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Logo/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveP1.setIcon(icon1)
        self.btnSaveP1.setObjectName(_fromUtf8("btnSaveP1"))
        self.verticalLayout_9.addWidget(self.btnSaveP1)
        self.Position1X = QtGui.QLineEdit(self.layoutWidget)
        self.Position1X.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.Position1X.setAlignment(QtCore.Qt.AlignCenter)
        self.Position1X.setObjectName(_fromUtf8("Position1X"))
        self.verticalLayout_9.addWidget(self.Position1X)
        self.Position1Y = QtGui.QLineEdit(self.layoutWidget)
        self.Position1Y.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.Position1Y.setAlignment(QtCore.Qt.AlignCenter)
        self.Position1Y.setObjectName(_fromUtf8("Position1Y"))
        self.verticalLayout_9.addWidget(self.Position1Y)
        self.Position1Z = QtGui.QLineEdit(self.layoutWidget)
        self.Position1Z.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.Position1Z.setAlignment(QtCore.Qt.AlignCenter)
        self.Position1Z.setObjectName(_fromUtf8("Position1Z"))
        self.verticalLayout_9.addWidget(self.Position1Z)
        self.btnGoP1 = QtGui.QPushButton(self.layoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Logo/Button-Next-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGoP1.setIcon(icon2)
        self.btnGoP1.setObjectName(_fromUtf8("btnGoP1"))
        self.verticalLayout_9.addWidget(self.btnGoP1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.btnSaveP2 = QtGui.QPushButton(self.layoutWidget)
        self.btnSaveP2.setIcon(icon1)
        self.btnSaveP2.setObjectName(_fromUtf8("btnSaveP2"))
        self.verticalLayout_10.addWidget(self.btnSaveP2)
        self.Position2X = QtGui.QLineEdit(self.layoutWidget)
        self.Position2X.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.Position2X.setAlignment(QtCore.Qt.AlignCenter)
        self.Position2X.setObjectName(_fromUtf8("Position2X"))
        self.verticalLayout_10.addWidget(self.Position2X)
        self.Position2Y = QtGui.QLineEdit(self.layoutWidget)
        self.Position2Y.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.Position2Y.setAlignment(QtCore.Qt.AlignCenter)
        self.Position2Y.setObjectName(_fromUtf8("Position2Y"))
        self.verticalLayout_10.addWidget(self.Position2Y)
        self.Position2Z = QtGui.QLineEdit(self.layoutWidget)
        self.Position2Z.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.Position2Z.setAlignment(QtCore.Qt.AlignCenter)
        self.Position2Z.setObjectName(_fromUtf8("Position2Z"))
        self.verticalLayout_10.addWidget(self.Position2Z)
        self.btnGoP2 = QtGui.QPushButton(self.layoutWidget)
        self.btnGoP2.setIcon(icon2)
        self.btnGoP2.setObjectName(_fromUtf8("btnGoP2"))
        self.verticalLayout_10.addWidget(self.btnGoP2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.btnSaveP3 = QtGui.QPushButton(self.layoutWidget)
        self.btnSaveP3.setIcon(icon1)
        self.btnSaveP3.setObjectName(_fromUtf8("btnSaveP3"))
        self.verticalLayout_11.addWidget(self.btnSaveP3)
        self.Position3X = QtGui.QLineEdit(self.layoutWidget)
        self.Position3X.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.Position3X.setAlignment(QtCore.Qt.AlignCenter)
        self.Position3X.setObjectName(_fromUtf8("Position3X"))
        self.verticalLayout_11.addWidget(self.Position3X)
        self.Position3Y = QtGui.QLineEdit(self.layoutWidget)
        self.Position3Y.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.Position3Y.setAlignment(QtCore.Qt.AlignCenter)
        self.Position3Y.setObjectName(_fromUtf8("Position3Y"))
        self.verticalLayout_11.addWidget(self.Position3Y)
        self.Position3Z = QtGui.QLineEdit(self.layoutWidget)
        self.Position3Z.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.Position3Z.setAlignment(QtCore.Qt.AlignCenter)
        self.Position3Z.setObjectName(_fromUtf8("Position3Z"))
        self.verticalLayout_11.addWidget(self.Position3Z)
        self.btnGoP3 = QtGui.QPushButton(self.layoutWidget)
        self.btnGoP3.setIcon(icon2)
        self.btnGoP3.setObjectName(_fromUtf8("btnGoP3"))
        self.verticalLayout_11.addWidget(self.btnGoP3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 460, 31, 61))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_12.setContentsMargins(-1, -1, -1, 1)
        self.verticalLayout_12.setSpacing(3)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_12.addWidget(self.label)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_12.addWidget(self.label_6)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_12.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 50, 541, 371))
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet(_fromUtf8("background: transparent;"))
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setPixmap(QtGui.QPixmap(_fromUtf8("Logo/micro H repère.jpg")))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.btnsettings = QtGui.QPushButton(self.centralwidget)
        self.btnsettings.setGeometry(QtCore.QRect(630, 510, 41, 41))
        self.btnsettings.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Logo/3107b825-90be-4ae6-8b9f-d4a29a72419f.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnsettings.setIcon(icon3)
        self.btnsettings.setIconSize(QtCore.QSize(41, 70))
        self.btnsettings.setObjectName(_fromUtf8("btnsettings"))
        self.btnMicromode = QtGui.QPushButton(self.centralwidget)
        self.btnMicromode.setGeometry(QtCore.QRect(570, 13, 75, 23))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("Logo/support14.3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMicromode.setIcon(icon4)
        self.btnMicromode.setIconSize(QtCore.QSize(12, 12))
        self.btnMicromode.setObjectName(_fromUtf8("btnMicromode"))
        self.btnSetzero = QtGui.QPushButton(self.centralwidget)
        self.btnSetzero.setGeometry(QtCore.QRect(560, 170, 101, 24))
        self.btnSetzero.setObjectName(_fromUtf8("btnSetzero"))
        self.btnSYZ = QtGui.QPushButton(self.centralwidget)
        self.btnSYZ.setGeometry(QtCore.QRect(450, 60, 81, 81))
        self.btnSYZ.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("Logo/icon-manual-mode.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSYZ.setIcon(icon5)
        self.btnSYZ.setIconSize(QtCore.QSize(70, 70))
        self.btnSYZ.setObjectName(_fromUtf8("btnSYZ"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(550, 580, 121, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.labelSYZ = QtGui.QLabel(self.centralwidget)
        self.labelSYZ.setGeometry(QtCore.QRect(445, 140, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelSYZ.setFont(font)
        self.labelSYZ.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSYZ.setObjectName(_fromUtf8("labelSYZ"))
        self.btnPosText = QtGui.QPushButton(self.centralwidget)
        self.btnPosText.setGeometry(QtCore.QRect(16, 440, 31, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Webdings"))
        font.setPointSize(17)
        self.btnPosText.setFont(font)
        self.btnPosText.setObjectName(_fromUtf8("btnPosText"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(430, 440, 171, 101))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(5, 14, 161, 81))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_RubyCurr_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_RubyCurr_2.setObjectName(_fromUtf8("label_RubyCurr_2"))
        self.gridLayout.addWidget(self.label_RubyCurr_2, 0, 2, 1, 1)
        self.label_RubyCurr = QtGui.QLabel(self.layoutWidget2)
        self.label_RubyCurr.setObjectName(_fromUtf8("label_RubyCurr"))
        self.gridLayout.addWidget(self.label_RubyCurr, 0, 0, 1, 1)
        self.label_RubyGpa = QtGui.QLabel(self.layoutWidget2)
        self.label_RubyGpa.setObjectName(_fromUtf8("label_RubyGpa"))
        self.gridLayout.addWidget(self.label_RubyGpa, 1, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.label_RubyGpa_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_RubyGpa_2.setObjectName(_fromUtf8("label_RubyGpa_2"))
        self.gridLayout.addWidget(self.label_RubyGpa_2, 1, 2, 1, 1)
        self.toolButton = QtGui.QToolButton(self.layoutWidget2)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.gridLayout.addWidget(self.toolButton, 2, 2, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(550, 200, 121, 111))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.SetpositionX = QtGui.QLineEdit(self.layoutWidget3)
        self.SetpositionX.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.SetpositionX.setAlignment(QtCore.Qt.AlignCenter)
        self.SetpositionX.setObjectName(_fromUtf8("SetpositionX"))
        self.gridLayout_2.addWidget(self.SetpositionX, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 1, 0, 1, 1)
        self.SetpositionY = QtGui.QLineEdit(self.layoutWidget3)
        self.SetpositionY.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.SetpositionY.setAlignment(QtCore.Qt.AlignCenter)
        self.SetpositionY.setObjectName(_fromUtf8("SetpositionY"))
        self.gridLayout_2.addWidget(self.SetpositionY, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.SetpositionZ = QtGui.QLineEdit(self.layoutWidget3)
        self.SetpositionZ.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.SetpositionZ.setAlignment(QtCore.Qt.AlignCenter)
        self.SetpositionZ.setObjectName(_fromUtf8("SetpositionZ"))
        self.gridLayout_2.addWidget(self.SetpositionZ, 2, 1, 1, 1)
        self.btnSetX = QtGui.QPushButton(self.layoutWidget3)
        self.btnSetX.setIcon(icon2)
        self.btnSetX.setObjectName(_fromUtf8("btnSetX"))
        self.gridLayout_2.addWidget(self.btnSetX, 3, 1, 1, 1)
        self.layoutWidget4 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(552, 70, 121, 101))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.btnReadX = QtGui.QPushButton(self.layoutWidget4)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("Logo/478027-glasses-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReadX.setIcon(icon6)
        self.btnReadX.setObjectName(_fromUtf8("btnReadX"))
        self.gridLayout_3.addWidget(self.btnReadX, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.positionX = QtGui.QLineEdit(self.layoutWidget4)
        self.positionX.setAlignment(QtCore.Qt.AlignCenter)
        self.positionX.setObjectName(_fromUtf8("positionX"))
        self.gridLayout_3.addWidget(self.positionX, 1, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 2, 0, 1, 1)
        self.positionY = QtGui.QLineEdit(self.layoutWidget4)
        self.positionY.setAlignment(QtCore.Qt.AlignCenter)
        self.positionY.setObjectName(_fromUtf8("positionY"))
        self.gridLayout_3.addWidget(self.positionY, 2, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 3, 0, 1, 1)
        self.positionZ = QtGui.QLineEdit(self.layoutWidget4)
        self.positionZ.setAlignment(QtCore.Qt.AlignCenter)
        self.positionZ.setObjectName(_fromUtf8("positionZ"))
        self.gridLayout_3.addWidget(self.positionZ, 3, 1, 1, 1)
        self.layoutWidget5 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(11, 561, 491, 41))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.radioButton_1 = QtGui.QRadioButton(self.layoutWidget5)
        self.radioButton_1.setChecked(True)
        self.radioButton_1.setAutoExclusive(False)
        self.radioButton_1.setObjectName(_fromUtf8("radioButton_1"))
        self.gridLayout_5.addWidget(self.radioButton_1, 0, 0, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.layoutWidget5)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout_5.addWidget(self.radioButton_2, 0, 1, 1, 1)
        self.radioButton_3 = QtGui.QRadioButton(self.layoutWidget5)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.gridLayout_5.addWidget(self.radioButton_3, 0, 2, 1, 1)
        self.radioButton_4 = QtGui.QRadioButton(self.layoutWidget5)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.gridLayout_5.addWidget(self.radioButton_4, 0, 3, 1, 1)
        self.radioButton_5 = QtGui.QRadioButton(self.layoutWidget5)
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.gridLayout_5.addWidget(self.radioButton_5, 0, 4, 1, 1)
        self.radioButton_6 = QtGui.QRadioButton(self.layoutWidget5)
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.gridLayout_5.addWidget(self.radioButton_6, 0, 5, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget5)
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 0, 6, 1, 1)
        self.btnAll = QtGui.QPushButton(self.layoutWidget5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnAll.setPalette(palette)
        self.btnAll.setObjectName(_fromUtf8("btnAll"))
        self.gridLayout_5.addWidget(self.btnAll, 0, 7, 1, 1)
        self.layoutWidget6 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(1, 9, 261, 31))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_8 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.radioButton_Raman = QtGui.QRadioButton(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_Raman.setFont(font)
        self.radioButton_Raman.setObjectName(_fromUtf8("radioButton_Raman"))
        self.gridLayout_4.addWidget(self.radioButton_Raman, 0, 1, 1, 1)
        self.radioButton_IR = QtGui.QRadioButton(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_IR.setFont(font)
        self.radioButton_IR.setChecked(False)
        self.radioButton_IR.setAutoExclusive(True)
        self.radioButton_IR.setObjectName(_fromUtf8("radioButton_IR"))
        self.gridLayout_4.addWidget(self.radioButton_IR, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget6)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 3, 1, 1)
        self.layoutWidget7 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget7.setGeometry(QtCore.QRect(290, 9, 274, 31))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget7)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_7 = QtGui.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.radioButton_Camera = QtGui.QRadioButton(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_Camera.setFont(font)
        self.radioButton_Camera.setAutoExclusive(True)
        self.radioButton_Camera.setObjectName(_fromUtf8("radioButton_Camera"))
        self.gridLayout_6.addWidget(self.radioButton_Camera, 0, 1, 1, 1)
        self.radioButton_Schwa = QtGui.QRadioButton(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_Schwa.setFont(font)
        self.radioButton_Schwa.setChecked(False)
        self.radioButton_Schwa.setAutoExclusive(True)
        self.radioButton_Schwa.setObjectName(_fromUtf8("radioButton_Schwa"))
        self.gridLayout_6.addWidget(self.radioButton_Schwa, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget7)
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_6.addWidget(self.label_11, 0, 3, 1, 1)
        self.label_10.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.line.raise_()
        self.btnStop.raise_()
        self.line_2.raise_()
        self.line_5.raise_()
        self.layoutWidget.raise_()
        self.btnzb.raise_()
        self.stepZ.raise_()
        self.btnzh.raise_()
        self.btnyb.raise_()
        self.stepY.raise_()
        self.btnyh.raise_()
        self.btnsettings.raise_()
        self.layoutWidget.raise_()
        self.btnxh.raise_()
        self.btnxb.raise_()
        self.stepX.raise_()
        self.btnMicromode.raise_()
        self.btnSetzero.raise_()
        self.btnSYZ.raise_()
        self.label_2.raise_()
        self.labelSYZ.raise_()
        self.btnPosText.raise_()
        self.groupBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionSyzON = QtGui.QAction(MainWindow)
        self.actionSyzON.setObjectName(_fromUtf8("actionSyzON"))
        self.actionSend = QtGui.QAction(MainWindow)
        self.actionSend.setObjectName(_fromUtf8("actionSend"))
        self.actionGotoP1 = QtGui.QAction(MainWindow)
        self.actionGotoP1.setObjectName(_fromUtf8("actionGotoP1"))
        self.actionGotoP2 = QtGui.QAction(MainWindow)
        self.actionGotoP2.setObjectName(_fromUtf8("actionGotoP2"))
        self.actionGotoP3 = QtGui.QAction(MainWindow)
        self.actionGotoP3.setObjectName(_fromUtf8("actionGotoP3"))
        self.actionClickSchwa = QtGui.QAction(MainWindow)
        self.actionClickSchwa.setObjectName(_fromUtf8("actionClickSchwa"))
        self.actionClickRaman = QtGui.QAction(MainWindow)
        self.actionClickRaman.setObjectName(_fromUtf8("actionClickRaman"))
        self.actionClickCamera = QtGui.QAction(MainWindow)
        self.actionClickCamera.setObjectName(_fromUtf8("actionClickCamera"))
        self.actionClickIR = QtGui.QAction(MainWindow)
        self.actionClickIR.setObjectName(_fromUtf8("actionClickIR"))
        self.actionAllON = QtGui.QAction(MainWindow)
        self.actionAllON.setObjectName(_fromUtf8("actionAllON"))
        self.menuMenu.addAction(self.actionClose)
        self.menu.addAction(self.actionSyzON)
        self.menu.addAction(self.actionAllON)
        self.menu.addAction(self.actionSend)
        self.menu.addSeparator()
        self.menu.addAction(self.actionGotoP1)
        self.menu.addAction(self.actionGotoP2)
        self.menu.addAction(self.actionGotoP3)
        self.menu.addSeparator()
        self.menu.addAction(self.actionClickSchwa)
        self.menu.addAction(self.actionClickRaman)
        self.menu.addAction(self.actionClickCamera)
        self.menu.addAction(self.actionClickIR)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL(_fromUtf8("triggered()")), self.btnStop.click)
        QtCore.QObject.connect(self.actionSend, QtCore.SIGNAL(_fromUtf8("triggered()")), self.btnMicromode.click)
        QtCore.QObject.connect(self.actionAllON, QtCore.SIGNAL(_fromUtf8("triggered()")), self.btnAll.click)
        QtCore.QObject.connect(self.actionSyzON, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.btnSYZ.click)
        QtCore.QObject.connect(self.actionGotoP1, QtCore.SIGNAL(_fromUtf8("triggered()")), self.btnGoP1.click)
        QtCore.QObject.connect(self.actionGotoP2, QtCore.SIGNAL(_fromUtf8("triggered()")), self.btnGoP2.click)
        QtCore.QObject.connect(self.actionGotoP3, QtCore.SIGNAL(_fromUtf8("triggered()")), self.btnGoP3.click)
        QtCore.QObject.connect(self.actionClickRaman, QtCore.SIGNAL(_fromUtf8("triggered()")), self.radioButton_Raman.click)
        QtCore.QObject.connect(self.actionClickIR, QtCore.SIGNAL(_fromUtf8("triggered()")), self.radioButton_IR.click)
        QtCore.QObject.connect(self.actionClickCamera, QtCore.SIGNAL(_fromUtf8("triggered()")), self.radioButton_Camera.click)
        QtCore.QObject.connect(self.actionClickSchwa, QtCore.SIGNAL(_fromUtf8("triggered()")), self.radioButton_Schwa.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btnStop, self.btnyb)
        MainWindow.setTabOrder(self.btnyb, self.btnyh)
        MainWindow.setTabOrder(self.btnyh, self.btnzb)
        MainWindow.setTabOrder(self.btnzb, self.btnzh)
        MainWindow.setTabOrder(self.btnzh, self.stepY)
        MainWindow.setTabOrder(self.stepY, self.stepZ)
        MainWindow.setTabOrder(self.stepZ, self.radioButton_IR)
        MainWindow.setTabOrder(self.radioButton_IR, self.radioButton_Schwa)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Horizon", None))
        self.btnStop.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#aa0000;\">STOP</span></p></body></html>", None))
        self.btnxh.setText(_translate("MainWindow", "►", None))
        self.btnxb.setText(_translate("MainWindow", "◄", None))
        self.btnyb.setText(_translate("MainWindow", "◄", None))
        self.btnyh.setText(_translate("MainWindow", "►", None))
        self.btnzb.setText(_translate("MainWindow", "▼", None))
        self.btnzh.setText(_translate("MainWindow", "▲", None))
        self.stepX.setText(_translate("MainWindow", "100", None))
        self.stepY.setText(_translate("MainWindow", "100", None))
        self.stepZ.setText(_translate("MainWindow", "100", None))
        self.btnSaveP1.setText(_translate("MainWindow", "  Save P1", None))
        self.btnGoP1.setText(_translate("MainWindow", "Go to P1", None))
        self.btnSaveP2.setText(_translate("MainWindow", "  Save P2", None))
        self.btnGoP2.setText(_translate("MainWindow", "Go to P2", None))
        self.btnSaveP3.setText(_translate("MainWindow", "  Save P3", None))
        self.btnGoP3.setText(_translate("MainWindow", "Go to P3", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">S</span></p></body></html>", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Y</span></p></body></html>", None))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Z</span></p></body></html>", None))
        self.btnMicromode.setText(_translate("MainWindow", "  Send", None))
        self.btnSetzero.setText(_translate("MainWindow", "Set Zero", None))
        self.label_2.setText(_translate("MainWindow", "Matthias Glachant (2016)", None))
        self.labelSYZ.setText(_translate("MainWindow", "Turn SYZ OFF", None))
        self.btnPosText.setText(_translate("MainWindow", "`", None))
        self.groupBox.setTitle(_translate("MainWindow", "Ruby Pressure Calculator", None))
        self.label_RubyCurr_2.setText(_translate("MainWindow", "nm", None))
        self.label_RubyCurr.setText(_translate("MainWindow", "Ruby FL", None))
        self.label_RubyGpa.setText(_translate("MainWindow", "Pressure", None))
        self.label_RubyGpa_2.setText(_translate("MainWindow", "GPa", None))
        self.toolButton.setText(_translate("MainWindow", "Settings", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">S</span></p></body></html>", None))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Y</span></p></body></html>", None))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Z</span></p></body></html>", None))
        self.btnSetX.setText(_translate("MainWindow", "Send here", None))
        self.btnReadX.setText(_translate("MainWindow", "Read", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">S</span></p></body></html>", None))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Y</span></p></body></html>", None))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Z</span></p></body></html>", None))
        self.radioButton_1.setText(_translate("MainWindow", "Raman", None))
        self.radioButton_2.setText(_translate("MainWindow", "Schwarzschild", None))
        self.radioButton_3.setText(_translate("MainWindow", "DAC", None))
        self.radioButton_4.setText(_translate("MainWindow", "S", None))
        self.radioButton_5.setText(_translate("MainWindow", " Y", None))
        self.radioButton_6.setText(_translate("MainWindow", " Z", None))
        self.btnAll.setText(_translate("MainWindow", "Change the status of all motors", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Microscope mode:</span></p></body></html>", None))
        self.radioButton_Raman.setText(_translate("MainWindow", "Raman", None))
        self.radioButton_IR.setText(_translate("MainWindow", "IR", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">DAC position:</span></p></body></html>", None))
        self.radioButton_Camera.setText(_translate("MainWindow", "Camera", None))
        self.radioButton_Schwa.setText(_translate("MainWindow", "Schwarzschild", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.menu.setTitle(_translate("MainWindow", "-", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionClose.setShortcut(_translate("MainWindow", "Esc", None))
        self.actionSyzON.setText(_translate("MainWindow", "SyzON", None))
        self.actionSyzON.setShortcut(_translate("MainWindow", "Alt+D", None))
        self.actionSend.setText(_translate("MainWindow", "Send", None))
        self.actionSend.setShortcut(_translate("MainWindow", "Alt+E", None))
        self.actionGotoP1.setText(_translate("MainWindow", "GotoP1", None))
        self.actionGotoP1.setShortcut(_translate("MainWindow", "Alt+F1", None))
        self.actionGotoP2.setText(_translate("MainWindow", "GotoP2", None))
        self.actionGotoP2.setShortcut(_translate("MainWindow", "Alt+F2", None))
        self.actionGotoP3.setText(_translate("MainWindow", "GotoP3", None))
        self.actionGotoP3.setShortcut(_translate("MainWindow", "Alt+F3", None))
        self.actionClickSchwa.setText(_translate("MainWindow", "ClickSchwa", None))
        self.actionClickSchwa.setShortcut(_translate("MainWindow", "S", None))
        self.actionClickRaman.setText(_translate("MainWindow", "ClickRaman", None))
        self.actionClickRaman.setShortcut(_translate("MainWindow", "R", None))
        self.actionClickCamera.setText(_translate("MainWindow", "ClickCamera", None))
        self.actionClickCamera.setShortcut(_translate("MainWindow", "C", None))
        self.actionClickIR.setText(_translate("MainWindow", "ClickIR", None))
        self.actionClickIR.setShortcut(_translate("MainWindow", "I", None))
        self.actionAllON.setText(_translate("MainWindow", "AllON", None))
        self.actionAllON.setShortcut(_translate("MainWindow", "Alt+A", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

